"""test alembic

Revision ID: d35329a8301c
Revises: cdbd0e9fddc9
Create Date: 2026-06-29 20:16:00.171094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd35329a8301c'
down_revision: Union[str, Sequence[str], None] = 'cdbd0e9fddc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.drop_index(op.f('ix_technology_candidate_requests_id'), table_name='technology_candidate_requests')
    op.drop_table('technology_candidate_requests')
    op.alter_column('ai_evaluations', 'technology_summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ai_evaluations', 'calgary_problem',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ai_evaluations', 'global_examples',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ai_evaluations', 'implementation_statistics',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ai_evaluations', 'governance_recommendation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('ai_evaluations', 'operational_excellence')
    op.drop_column('ai_evaluations', 'people_culture')
    op.drop_column('ai_evaluations', 'innovation_agility')
    op.drop_column('ai_evaluations', 'financial_sustainability')
    op.add_column('applications', sa.Column('event_title', sa.String(), nullable=True))
    op.alter_column('calgary_challenge_votes', 'submission_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_challenge_votes_submission'), 'calgary_challenge_votes', type_='foreignkey')
    op.alter_column('challenge_application_links', 'challenge',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'challenge_application_links', 'technology_applications', ['application_id'], ['id'])
    op.drop_index(op.f('ix_community_signals_submission_id'), table_name='community_signals')
    op.alter_column('technologies', 'hero_image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_technologies_id'), 'technologies', ['id'], unique=False)
    op.drop_column('technologies', 'current_status')
    op.drop_column('technology_applications', 'status')
    op.drop_index(op.f('ix_votes_submission_id'), table_name='votes')
    op.drop_column('votes', 'innovation_agility')
    op.drop_column('votes', 'operational_excellence')
    op.drop_column('votes', 'trusted_government')
    op.drop_column('votes', 'financial_sustainability')
    op.drop_column('votes', 'people_culture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('people_culture', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('financial_sustainability', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('trusted_government', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('operational_excellence', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('votes', sa.Column('innovation_agility', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_votes_submission_id'), 'votes', ['submission_id'], unique=False)
    op.add_column('technology_applications', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('technologies', sa.Column('current_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_technologies_id'), table_name='technologies')
    op.alter_column('technologies', 'hero_image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('ix_community_signals_submission_id'), 'community_signals', ['submission_id'], unique=False)
    op.drop_constraint(None, 'challenge_application_links', type_='foreignkey')
    op.alter_column('challenge_application_links', 'challenge',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_challenge_votes_submission'), 'calgary_challenge_votes', 'community_submissions', ['submission_id'], ['id'])
    op.alter_column('calgary_challenge_votes', 'submission_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('applications', 'event_title')
    op.add_column('ai_evaluations', sa.Column('financial_sustainability', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_evaluations', sa.Column('innovation_agility', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_evaluations', sa.Column('people_culture', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_evaluations', sa.Column('operational_excellence', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('ai_evaluations', 'governance_recommendation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_evaluations', 'implementation_statistics',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_evaluations', 'global_examples',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_evaluations', 'calgary_problem',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_evaluations', 'technology_summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('technology_candidate_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('technology_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('technology_candidate_requests_pkey'))
    )
    op.create_index(op.f('ix_technology_candidate_requests_id'), 'technology_candidate_requests', ['id'], unique=False)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
